mtd: rawnand: ingenic: Fix build when mixing built-in/modules
When the Ingenic NAND controller driver is compiled-in while the ECC
drivers are compiled as modules, the following happens:

drivers/mtd/nand/raw/ingenic/ingenic_nand.o: In function `ingenic_nand_remove':
ingenic_nand.c:(.text+0x12c): undefined reference to `ingenic_ecc_release'
drivers/mtd/nand/raw/ingenic/ingenic_nand.o: In function `ingenic_nand_ecc_correct':
ingenic_nand.c:(.text+0x17c): undefined reference to `ingenic_ecc_correct'
drivers/mtd/nand/raw/ingenic/ingenic_nand.o: In function `ingenic_nand_ecc_calculate':
ingenic_nand.c:(.text+0x1f0): undefined reference to `ingenic_ecc_calculate'
drivers/mtd/nand/raw/ingenic/ingenic_nand.o: In function `ingenic_nand_probe':
ingenic_nand.c:(.text+0x50c): undefined reference to `of_ingenic_ecc_get'
ingenic_nand.c:(.text+0x59c): undefined reference to `ingenic_ecc_release'

This is because functions defined in ingenic_ecc.c are called from
ingenic_nand.c while the symbol for compiling ingenic_ecc.c is
selected only by the ECC drivers. As ingenic_ecc and ingenic_nand are
tightly connected, build them both at the same time. This will nicely
fix the build issue and also remove some boilerplate.

Signed-off-by: Miquel Raynal <miquel.raynal@bootlin.com>